const focusKeys = ["個人發展", "社會發展", "商務發展", "國際發展"];
const satisfactionOrder = ["非常滿意", "滿意", "一般", "有改進空間", "未曾參與今年活動"];
const newProgrammes = {
  "AI與數位": "AI 與數位工具領袖應用工作坊",
  "青年精神健康": "青年精神健康與心理",
  "綠色永續": "綠色永續與企業 ESG 實踐專案",
  "姊妹會": "姊妹會深度交流與聯合工作計劃",
  "初創創業": "初創創業路演與跨界商務對接",
  "體育聯賽": "體育聯賽／戶外團隊建立"
};
const short = {"AI與數位":"AI 與數位工具","青年精神健康":"青年精神健康","綠色永續":"綠色永續／ESG","姊妹會":"姊妹會交流","初創創業":"初創路演","體育聯賽":"團隊建立"};
const programmes = {"港日交流塾":"港日交流塾（日語基礎班）","項目管理爆SKILL":"從 I 到 TEAM：項目管理爆SKILL 營","幼教生存劇本殺":"幼教生存劇本殺"};
const roles = {"擔任工作計劃主席（Project Chairman )":"工作計劃主席","擔任籌委會成員（OC Member）":"籌委會成員","嘗試擔任董事局成員（Board Member）":"董事局成員","以參加者/會友身份支持活動":"參加者／會友支持","視乎時間再作安排":"視乎時間安排"};
const align = {"AI與數位":[[0,2,0,2],"領導力發展、數據驅動創新",["SDG 4","SDG 8","SDG 9"]],"青年精神健康":[[1,1,2,0],"組織可持續",["SDG 3","SDG 10","SDG 11"]],"綠色永續":[[2,1,2,2],"品牌可見度、組織可持續、數據驅動創新",["SDG 12","SDG 13","SDG 17"]],"姊妹會":[[2,1,1,0],"品牌可見度、領導力發展",["SDG 4","SDG 17"]],"初創創業":[[2,2,1,1],"品牌可見度、領導力發展",["SDG 8","SDG 9","SDG 17"]],"體育聯賽":[[0,1,2,0],"組織可持續",["SDG 3","SDG 10"]]};
const membership = [{label:"正式會員",value:100},{label:"總會資深商會會員",value:86},{label:"浩洋資深青商會員",value:63}];
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const count = (rows, field, term) => rows.filter(row => String(row[field] || '').includes(term)).length;
const frequency = values => values.reduce((map, value) => (map[value] = (map[value] || 0) + 1, map), {});
function gradient(intensity){const stops=[[214,212,203],[217,175,154],[232,133,97],[255,91,32]];const p=intensity*(stops.length-1),l=Math.floor(p),u=Math.min(l+1,stops.length-1),f=p-l;const rgb=stops[l].map((v,i)=>Math.round(v+(stops[u][i]-v)*f));return `rgb(${rgb.join(',')})`}
function lollipop(data){const max=Math.max(...data.map(x=>x.value),1);return data.map(x=>`<div class="lollipop-row"><span class="chart-label">${escapeHtml(x.label)}</span><span class="lollipop-track"><i class="lollipop-line" style="width:${x.value/max*100}%"></i><i class="lollipop-dot" style="left:${x.value/max*100}%"></i></span><span class="chart-value">${x.value}</span></div>`).join('')}
function scale(data){const max=Math.max(...data.map(x=>x.value),1);return data.map(x=>`<div class="scale-row"><span class="chart-label">${escapeHtml(x.label)}</span><span class="scale-dots">${Array.from({length:max},(_,i)=>`<i class="scale-dot ${i<x.value?'on':''}"></i>`).join('')}</span><span class="chart-value">${x.value}</span></div>`).join('')}
function bars(data, denominator){const max=Math.max(...data.map(x=>x.value),1);return data.map(x=>`<div class="bar-row"><span class="chart-label">${escapeHtml(x.label)}</span><span class="bar-track"><i class="bar-fill" style="width:${x.value/max*100}%;background:${gradient(x.value/max)}"></i></span><span class="chart-value">${denominator?`${x.value} · ${Math.round(x.value/denominator*100)}%`:x.value}</span></div>`).join('')}
function symbols(data){const glyphs=['◉','◇','✦','○','◌'];return data.map((x,i)=>`<div class="symbol-row"><i class="symbol">${glyphs[i%glyphs.length]}</i><span class="symbol-label">${escapeHtml(x.label)}</span><strong>${x.value}</strong></div>`).join('')}
function renderMatrix(){const pillars=['品牌可見度','領導力發展','組織可持續','數據驅動創新'];let html='<div></div>'+pillars.map(x=>`<div class="head">${x}</div>`).join('');Object.entries(newProgrammes).forEach(([key,label])=>{html+=`<div class="name">${label}</div>`+align[key][0].map(score=>`<div class="${score===2?'direct':score===1?'support':''}">${score===2?'直接':score===1?'支援':''}</div>`).join('')});return html}
function render(rows){const focus=document.getElementById('focus').value,sat=document.getElementById('satisfaction').value;const filtered=rows.filter(row=>(focus==='全部'||String(row.development_focus||'').includes(focus))&&(sat==='全部'||row.satisfaction===sat));const programmeData=Object.entries(newProgrammes).map(([key,label])=>({key,label,value:count(filtered,'new_programmes',key)})).sort((a,b)=>b.value-a.value);const top=programmeData[0].value;document.getElementById('top-signal').innerHTML=`<mark>${programmeData.filter(x=>x.value===top).slice(0,2).map(x=>short[x.key]).join('、')}</mark>`;document.getElementById('focus-chart').innerHTML=lollipop(focusKeys.map(label=>({label,value:count(filtered,'development_focus',label)})).sort((a,b)=>a.value-b.value));const satRows=satisfactionOrder.map(label=>({label,value:filtered.filter(row=>row.satisfaction===label).length}));document.getElementById('satisfaction-chart').innerHTML=scale(satRows);const answered=filtered.filter(row=>row.satisfaction);const positive=answered.filter(row=>['滿意','非常滿意'].includes(row.satisfaction)).length;document.getElementById('positive-rate').textContent=answered.length?`${Math.round(positive/answered.length*100)}%`:'0%';document.getElementById('memory-chart').innerHTML=symbols(Object.entries(programmes).map(([key,label])=>({label,value:count(filtered,'memorable_programmes',key)})).sort((a,b)=>b.value-a.value));document.getElementById('programme-chart').innerHTML=bars(programmeData,filtered.length);const roleCounts=frequency(filtered.map(row=>row.future_role).filter(Boolean));document.getElementById('role-chart').innerHTML=symbols(Object.entries(roleCounts).map(([key,value])=>({label:roles[key]||key,value})).sort((a,b)=>b.value-a.value));document.getElementById('strategy-matrix').innerHTML=renderMatrix();document.getElementById('sdg-list').innerHTML=Object.entries(newProgrammes).map(([key,label])=>`<div class="sdg-row"><strong>${label}</strong><span class="sdg-demand">${count(filtered,'new_programmes',key)}／${filtered.length}</span><span class="sdg-copy"><b>JCI 策略</b><br>${align[key][1]}</span><span>${align[key][2].map(tag=>`<i class="tag">${tag}</i>`).join('')}</span></div>`).join('');document.getElementById('membership-chart').innerHTML=bars(membership,100)}
fetch('data/survey.json').then(response=>response.json()).then(rows=>{render(rows);document.querySelectorAll('select').forEach(select=>select.addEventListener('change',()=>render(rows)))});
